version: "3.8"

volumes:
  rabbitmq_data:

services:

  #######################################################
  # Portfolio : The Portfolio microservice (Done)
  #######################################################
  portfolio:
    build:
      context: ./
      dockerfile: portfolio.Dockerfile
    image: jordanteoh2020/portfolio:esd
    restart: always
    depends_on: # (Need to edit)
      - user
    environment:
      dbURL: mysql+mysqlconnector://root@host.docker.internal:3306/esdproject/portfolio
      PYTHONUNBUFFERED: 1

  ####################################
  # RabbitMQ: The messaging broker   (DONE)
  ####################################
  rabbitmq:
    image: rabbitmq:3-management
    hostname: esd-rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes: 
      - rabbitmq_data:/var/lib/rabbitmq
      
  #################################################
  # Logging: The Logging microservice (DONE)
  #################################################
  # logging:
  #   build:
  #     context: ./
  #     dockerfile: logging.Dockerfile
  #   image: jordanteoh2020/logging:esd
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     rabbit_host: rabbitmq
  #     rabbit_port: 5672
  #     PYTHONUNBUFFERED: 1

  ###################################
  # Error: The Error microservice
  ###################################
  # error:
  #   build:
  #     context: ./
  #     dockerfile: error.Dockerfile
  #   image: jordanteoh2020/error:esd
  #   restart: always
  #   depends_on:
  #     - rabbitmq
  #   environment:
  #     rabbit_host: rabbitmq
  #     rabbit_port: 5672
  #     PYTHONUNBUFFERED: 1

  ###############################################
  # Place Order: The Place Order microservice (DONE)
  ###############################################
  place_order:
    build:
      context: ./
      dockerfile: place_order.Dockerfile
    image: jordanteoh2020/place_order:esd
    restart: always
    depends_on: # (Need to edit)
      - portfolio
      - stockinfo
    environment:
      rabbit_host: rabbitmq
      rabbit_port: 5672
      portfolio_URL: http://portfolio:5001/portfolio
      stockinfo_URL: http://stockinfo:5002/stockinfo 
      PYTHONUNBUFFERED: 1
    ports:
      - "5100:5100"

  ##################################
  # stockinfo: The Book microservice
  ##################################
  stockinfo:
    build:
      context: ./
      dockerfile: stockinfo.Dockerfile
    image: jordanteoh2020/stockinfo:esd
    restart: always
    environment:
      polygon_URL: https://api.polygon.io/v2/aggs/grouped/locale/us/market/stocks/2022-03-25?adjusted=true&apiKey=
      PYTHONUNBUFFERED: 1

  ###################################
  # Positions : The Positions microservice
  ###################################
  positions:
    build:
      context: ./
      dockerfile: positions.Dockerfile
    image: jordanteoh2020/positions:esd
    depends_on: # (Need to edit)
      - portfolio
      - user
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@localhost:3306/esdproject
      PYTHONUNBUFFERED: 1

    ###################################
  # Stock Recommender : The Stock Recommender microservice
  ###################################
  stock_recommender:
    build:
      context: ./
      dockerfile: stock_recommender.Dockerfile
    image: jordanteoh2020/stock_recommender:esd
    restart: always
    environment:
      URL: http://127.0.0.1:5000/stockinfo/get_all_stock_info/
      PYTHONUNBUFFERED: 1

    ###################################
  # User : The User microservice
  ###################################
  user:
    build:
      context: ./
      dockerfile: user.Dockerfile
    image: jordanteoh2020/user:esd
    depends_on: # (Need to edit)
      - signup_login
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@localhost:3306/esdproject
      PYTHONUNBUFFERED: 1

    ###################################
  # signup_login : The signup_login microservice
  ###################################
  signup_login:
    build:
      context: ./
      dockerfile: signup_login.Dockerfile
    image: jordanteoh2020/signup_login:esd
    restart: always
    environment:
      dbURL: mysql+mysqlconnector://root@localhost:3306/esdproject
      PYTHONUNBUFFERED: 1